In [ ]:
import seaborn as sns
import pandas as pd
import polars as pl

# Load dataset
diamonds = sns.load_dataset('diamonds')

In [ ]:
# create pandas dataframe and add a column

df_pd = pd.DataFrame(diamonds)
df_pd['USD_Euro_conversion'] = 0.92
df_pd

In [ ]:
# calculate a new column

df_pd['price_euro'] = df_pd['price'] * df_pd['USD_Euro_conversion']
df_pd

In [ ]:
# create polars dataframe and add a column

df_pl = pl.DataFrame(diamonds)
df_pl = df_pl.with_columns(pl.lit(0.92).alias('USD_Euro_conversion'))

In [ ]:
# calculate a new column

df_pl = df_pl.with_columns((df_pl['price'] * df_pl['USD_Euro_conversion']).alias('price_euro'))
df_pl

In [ ]:
# drop a column from pandas dataframe

df_pd = df_pd.drop(columns=['USD_Euro_conversion'])
df_pd

In [ ]:
# drop a column from polars dataframe

df_pl = df_pl.drop('USD_Euro_conversion')
df_pl

In [ ]:
# rename polars column name

df_pl = df_pl.rename({'price_euro': 'price_in_euros'})
df_pl

In [ ]:
# change column data type

df_pl.with_columns(pl.col("carat").cast(pl.Float32))